/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Directory containing default config */
#define CONFDIR "/usr/local/etc/elinks"

/* Define if you want: 256 colors support */
/* #undef CONFIG_256_COLORS */

/* Define if you want: 88 colors support */
/* #undef CONFIG_88_COLORS */

/* Define if you want: AsciiDoc support */
/* #undef CONFIG_ASCIIDOC */

/* Define if you want: Backtrace support */
#define CONFIG_BACKTRACE 1

/* Define if you want: BEOS support */
/* #undef CONFIG_BEOS */

/* Define if you want: BitTorrent protocol support */
/* #undef CONFIG_BITTORRENT */

/* Define if you want: Bookmarks support */
#define CONFIG_BOOKMARKS 1

/* Define if you want: bzlib support */
#define CONFIG_BZIP2 1

/* Define if you want: Local CGI support */
/* #undef CONFIG_CGI */

/* Define if you want: Cookies support */
#define CONFIG_COOKIES 1

/* Define if you want: Cascading Style Sheets support */
#define CONFIG_CSS 1

/* Define if you want: Data protocol support */
#define CONFIG_DATA 1

/* Define if you want: Debug mode support */
/* #undef CONFIG_DEBUG */

/* Define if you want: Documentation Tools support */
#define CONFIG_DOC 1

/* Define if you want: DOM engine support */
/* #undef CONFIG_DOM */

/* Define if you want: ECMAScript (JavaScript) support */
/* #undef CONFIG_ECMASCRIPT */

/* Define if you want: Exmode interface support */
/* #undef CONFIG_EXMODE */

/* Define if you want: Fast mode support */
/* #undef CONFIG_FASTMEM */

/* Define if you want: Finger protocol support */
/* #undef CONFIG_FINGER */

/* Define if you want: Form history support */
#define CONFIG_FORMHIST 1

/* Define if you want: FSP protocol support */
/* #undef CONFIG_FSP */

/* Define if you want: FTP protocol support */
#define CONFIG_FTP 1

/* Define if you want: Global history support */
#define CONFIG_GLOBHIST 1

/* Define if you want: GNUTLS support */
/* #undef CONFIG_GNUTLS */

/* Define if you want: GNU TLS OpenSSL compatibility support */
/* #undef CONFIG_GNUTLS_OPENSSL_COMPAT */

/* Define if you want: Gopher protocol support */
/* #undef CONFIG_GOPHER */

/* Define if you want: gpm support */
/* #undef CONFIG_GPM */

/* Define if you want: Guile support */
/* #undef CONFIG_GUILE */

/* Define if you want: zlib support */
#define CONFIG_GZIP 1

/* Define if you want: HTML highlighting support */
/* #undef CONFIG_HTML_HIGHLIGHT */

/* Define if you want: idn support */
/* #undef CONFIG_IDN */

/* Define if you want: interlinking support */
#define CONFIG_INTERLINK 1

/* Define if you want: IPv6 support */
#define CONFIG_IPV6 1

/* Define if you want: JadeWrapper support */
/* #undef CONFIG_JW */

/* Define if you want: LEDs support */
#define CONFIG_LEDS 1

/* Define if you want: Lua support */
/* #undef CONFIG_LUA */

/* Define if you want: Mailcap support */
#define CONFIG_MAILCAP 1

/* Define if you want: Man Page Formats support */
/* #undef CONFIG_MANPAGE */

/* Define if you want: Manual Formats support */
/* #undef CONFIG_MANUAL */

/* Define if you want: Marks support */
#define CONFIG_MARKS 1

/* Define if you want: Built-in MD5 support */
/* #undef CONFIG_MD5 */

/* Define if you want: Mimetypes files support */
#define CONFIG_MIMETYPES 1

/* Define if you want: Mouse handling support */
#define CONFIG_MOUSE 1

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
#define CONFIG_NLS 1

/* Define if you want: NNTP protocol support */
/* #undef CONFIG_NNTP */

/* Define if you want: No root exec support */
/* #undef CONFIG_NO_ROOT_EXEC */

/* Define if you want: OpenSSL support */
#define CONFIG_OPENSSL 1

/* Define if you want: EMX support */
/* #undef CONFIG_OS2 */

/* Define if you want: Own libc stubs support */
/* #undef CONFIG_OWN_LIBC */

/* Define if you want: Perl support */
/* #undef CONFIG_PERL */

/* Define if using Perl 5.8.8 or later, where the "POPpx" macro no longer
   needs an "n_a" variable like it did in 5.8.7 */
/* #undef CONFIG_PERL_POPPX_WITHOUT_N_A */

/* Define if you want: Pod2HTML support */
#define CONFIG_POD2HTML 1

/* Define if you want: Python support */
/* #undef CONFIG_PYTHON */

/* Define if you want: RISCOS support */
/* #undef CONFIG_RISCOS */

/* Define if you want: Ruby support */
/* #undef CONFIG_RUBY */

/* Define if you want: Built-in scanner support */
#define CONFIG_SCANNER 1

/* Define if you want: Browser scripting support */
/* #undef CONFIG_SCRIPTING */

/* Define if you want: Built-in SHA1 support */
/* #undef CONFIG_SHA1 */

/* Define if you want: Small binary support */
/* #undef CONFIG_SMALL */

/* Define if you want: SMB protocol support */
/* #undef CONFIG_SMB */

/* Define if you want: SpiderMonkey support */
/* #undef CONFIG_SM_SCRIPTING */

/* Define if you want: SpiderMonkey support */
/* #undef CONFIG_SPIDERMONKEY */

/* Define if you want: SSL support */
#define CONFIG_SSL 1

/* Define if you want: BSD sysmouse support */
/* #undef CONFIG_SYSMOUSE */

/* Define if you want: UNIX support */
#define CONFIG_UNIX 1

/* Define if you want: URI rewriting support */
#define CONFIG_URI_REWRITE 1

/* Define if you want: WIN32 support */
/* #undef CONFIG_WIN32 */

/* Define if you want: XBEL bookmarks support */
/* #undef CONFIG_XBEL_BOOKMARKS */

/* Define if you want: XmlTo support */
/* #undef CONFIG_XMLTO */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if you have the `access' function. */
#define HAVE_ACCESS 1

/* Define if you have struct addrinfo */
#define HAVE_ADDRINFO 1

/* Define to 1 if you have the `alarm' function. */
#define HAVE_ALARM 1

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <argz.h> header file. */
#define HAVE_ARGZ_H 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1

/* Define to 1 if you have the `bcopy' function. */
#define HAVE_BCOPY 1

/* Define if you have _beginthread() */
/* #undef HAVE_BEGINTHREAD */

/* Define to 1 if you have the <bzlib.h> header file. */
#define HAVE_BZLIB_H 1

/* Define if you have C99 compliant vsnprintf() */
#define HAVE_C99_VSNPRINTF 1

/* Define to 1 if you have the `chmod' function. */
#define HAVE_CHMOD 1

/* Define to 1 if you have the `clock_gettime' function. */
/* #undef HAVE_CLOCK_GETTIME */

/* Define to 1 if you have the `cygwin_conv_to_full_win32_path' function. */
/* #undef HAVE_CYGWIN_CONV_TO_FULL_WIN32_PATH */

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <execinfo.h> header file. */
#define HAVE_EXECINFO_H 1

/* Define to 1 if you have the <expat.h> header file. */
/* #undef HAVE_EXPAT_H */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `feof_unlocked' function. */
#define HAVE_FEOF_UNLOCKED 1

/* Define to 1 if you have the `fflush' function. */
#define HAVE_FFLUSH 1

/* Define to 1 if you have the `fgets_unlocked' function. */
#define HAVE_FGETS_UNLOCKED 1

/* Define to 1 if you have the `fseeko' function. */
#define HAVE_FSEEKO 1

/* Define to 1 if you have the <fsplib.h> header file. */
/* #undef HAVE_FSPLIB_H */

/* Define to 1 if you have the `fsync' function. */
#define HAVE_FSYNC 1

/* Define to 1 if you have the `ftello' function. */
#define HAVE_FTELLO 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `getegid' function. */
#define HAVE_GETEGID 1

/* Define to 1 if you have the `geteuid' function. */
#define HAVE_GETEUID 1

/* Define to 1 if you have the `getgid' function. */
#define HAVE_GETGID 1

/* Define to 1 if you have the `gethostbyaddr' function. */
#define HAVE_GETHOSTBYADDR 1

/* Define to 1 if you have the `getifaddrs' function. */
/* #undef HAVE_GETIFADDRS */

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `getpgid' function. */
#define HAVE_GETPGID 1

/* Define to 1 if you have the `getpgrp' function. */
#define HAVE_GETPGRP 1

/* Define to 1 if you have the `getpid' function. */
#define HAVE_GETPID 1

/* Define to 1 if you have the `getpwnam' function. */
#define HAVE_GETPWNAM 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `getuid' function. */
#define HAVE_GETUID 1

/* Define to 1 if you have the <gnutls/openssl.h> header file. */
/* #undef HAVE_GNUTLS_OPENSSL_H */

/* Define to 1 if you have the <gpm.h> header file. */
/* #undef HAVE_GPM_H */

/* Define to 1 if you have the `herror' function. */
#define HAVE_HERROR 1

/* Define if you have the iconv() function. */
#define HAVE_ICONV 1

/* Define to 1 if you have the <idna.h> header file. */
/* #undef HAVE_IDNA_H */

/* Define to 1 if you have the <ifaddrs.h> header file. */
/* #undef HAVE_IFADDRS_H */

/* Define to 1 if you have the `index' function. */
#define HAVE_INDEX 1

/* Define to 1 if you have the `inet_ntop' function. */
#define HAVE_INET_NTOP 1

/* Define to 1 if you have the `inet_pton' function. */
#define HAVE_INET_PTON 1

/* Define if you have int32_t */
#define HAVE_INT32_T 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <io.h> header file. */
/* #undef HAVE_IO_H */

/* Define to 1 if you have the `isdigit' function. */
#define HAVE_ISDIGIT 1

/* Define to 1 if you have the `kill' function. */
#define HAVE_KILL 1

/* Define if you have <langinfo.h> and nl_langinfo(CODESET). */
#define HAVE_LANGINFO_CODESET 1

/* Define to 1 if you have the <lauxlib.h> header file. */
/* #undef HAVE_LAUXLIB_H */

/* Define if your <locale.h> file defines LC_MESSAGES. */
#define HAVE_LC_MESSAGES 1

/* Define to 1 if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the `nsl' library (-lnsl). */
/* #undef HAVE_LIBNSL */

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define if you have long long */
#define HAVE_LONG_LONG 1

/* Define to 1 if you have the <machine/console.h> header file. */
/* #undef HAVE_MACHINE_CONSOLE_H */

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mempcpy' function. */
#define HAVE_MEMPCPY 1

/* Define to 1 if you have the `memrchr' function. */
#define HAVE_MEMRCHR 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define if you have MouOpen() */
/* #undef HAVE_MOUOPEN */

/* Define to 1 if you have the `mremap' function. */
#define HAVE_MREMAP 1

/* Define to 1 if you have the `munmap' function. */
#define HAVE_MUNMAP 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in6_var.h> header file. */
/* #undef HAVE_NETINET_IN6_VAR_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <netinet/in_system.h> header file. */
/* #undef HAVE_NETINET_IN_SYSTEM_H */

/* Define to 1 if you have the <netinet/in_systm.h> header file. */
#define HAVE_NETINET_IN_SYSTM_H 1

/* Define to 1 if you have the <netinet/ip.h> header file. */
#define HAVE_NETINET_IP_H 1

/* Define to 1 if you have the <net/if.h> header file. */
#define HAVE_NET_IF_H 1

/* Define to 1 if you have the <nl_types.h> header file. */
#define HAVE_NL_TYPES_H 1

/* Define if you have off_t */
#define HAVE_OFF_T 1

/* Define to 1 if you have the `popen' function. */
#define HAVE_POPEN 1

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the <pwd.h> header file. */
#define HAVE_PWD_H 1

/* Define to 1 if you have the `raise' function. */
#define HAVE_RAISE 1

/* Define if you have _read_kbd() */
/* #undef HAVE_READ_KBD */

/* Define if you have regex_t */
#define HAVE_REGEX_H 1

/* Define if you have struct sockaddr_in6 */
#define HAVE_SA_IN6 1

/* Define if you have struct sockaddr_storage */
#define HAVE_SA_STORAGE 1

/* Define if you have _SC_PAGE_SIZE */
#define HAVE_SC_PAGE_SIZE 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the `setpgid' function. */
#define HAVE_SETPGID 1

/* Define to 1 if you have the `setpgrp' function. */
#define HAVE_SETPGRP 1

/* Define to 1 if you have the `sigaction' function. */
#define HAVE_SIGACTION 1

/* Define to 1 if you have the <sigaction.h> header file. */
/* #undef HAVE_SIGACTION_H */

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `stpcpy' function. */
#define HAVE_STPCPY 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strcasestr' function. */
#define HAVE_STRCASESTR 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if you have the <sys/consio.h> header file. */
/* #undef HAVE_SYS_CONSIO_H */

/* Define to 1 if you have the <sys/cygwin.h> header file. */
/* #undef HAVE_SYS_CYGWIN_H */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/fmutex.h> header file. */
/* #undef HAVE_SYS_FMUTEX_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/signal.h> header file. */
#define HAVE_SYS_SIGNAL_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/un.h> header file. */
#define HAVE_SYS_UN_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the `timegm' function. */
#define HAVE_TIMEGM 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the `tsearch' function. */
#define HAVE_TSEARCH 1

/* Define if you have typeof */
#define HAVE_TYPEOF 1

/* Define if you have uint16_t */
#define HAVE_UINT16_T 1

/* Define if you have uint32_t */
#define HAVE_UINT32_T 1

/* Define to 1 if you have the `uname' function. */
#define HAVE_UNAME 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if you have variadic macros */
#define HAVE_VARIADIC_MACROS 1

/* Define to 1 if you have the `vasprintf' function. */
#define HAVE_VASPRINTF 1

/* Define if you have __va_copy */
#define HAVE_VA_COPY 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Define if you have X11 for restoring window titles */
/* #undef HAVE_X11 */

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Define to 1 if you have the `__argz_count' function. */
#define HAVE___ARGZ_COUNT 1

/* Define to 1 if you have the `__argz_next' function. */
#define HAVE___ARGZ_NEXT 1

/* Define to 1 if you have the `__argz_stringify' function. */
#define HAVE___ARGZ_STRINGIFY 1

/* Define as const if the declaration of iconv() needs const. */
#define ICONV_CONST 

/* Directory containing libraries */
#define LIBDIR "/usr/local/lib"

/* Directory containing locales */
#define LOCALEDIR "/usr/local/share/locale"

/* Define if you want: HTML (one file) support */
/* #undef MANUAL_ASCIIDOC */

/* Define if you want: PDF support */
/* #undef MANUAL_JW */

/* Define if you want: HTML (multiple files) support */
/* #undef MANUAL_XMLTO */

/* Define if you want: HTML support */
/* #undef MAN_ASCIIDOC */

/* Define if you want: man (groff) support */
/* #undef MAN_XMLTO */

/* Package version */
#define PACKAGE "elinks"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `off_t', as computed by sizeof. */
#define SIZEOF_OFF_T 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Package version */
#define VERSION "0.11.4"

/* Define if you have XFree under OS/2 */
/* #undef X2 */

/* How to invoke XTerm */
/* #undef XTERM */

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to int if <sys/types.h> doesn't define. */
/* #undef ssize_t */
