#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > test.html
<!DOCTYPE html>
<html>
<head>
<title>freshcode.club</title>
<meta charset=UTF-8>
<b>🐦</b> t</span> <a href="/">@tracker</a>
<div><a href="/">AAA</a></div>
</body>
</html>
EOF

cat <<EOF > ref-dump
   🐦 t [1]@tracker
   [2]AAA

References

   Visible links
   1. file:///
   2. file:///
EOF

elinks -dump -dump-width 80  test.html | diff -q - ref-dump
echo "dump: OK"
