#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
screen -ls || true
HOME=$WORKDIR screen -d -m elinks -config-dir $WORKDIR
echo "POST SCREEN"
echo "screens:"
screen -ls
echo "procs:"
if pgrep elinks; then
  ps -l `pgrep elinks`
fi
echo "ls:"
ls -l $WORKDIR
HOME=$WORKDIR elinks -config-dir $WORKDIR -remote "ping()"
echo "run: OK"
